# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 296f919c1a67927f5ff3219092aac15f65d7818c3e3cf03f7581dd6cffc59bd3362c1ec493ee8e036c5ceec8922159a65daf93c3c480fbffb0b122d375df7eda

test:
  secret_key_base: 4b5a2795635225a057ad9b03ac9d70a4e85753879ae0992701afc6f8b43731a8981478719cc23588fa110112db5ccdfdfa2e8c281840e347d0ae1274fe71ce4b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
